export const questions = [
  { label: "בוא נתחיל בשמך – איך נכתוב אותך בתור בעל הבית? 🙂", name: "fullName", type: "text", placeholder: "כמו בתעודת זהות – שם פרטי + שם משפחה" },
  { label: "מה מספר תעודת הזהות של בעל הדירה?", name: "idNumber", type: "text", placeholder: "מספר ת.ז. של בעל הדירה" },
  { label: "ואיך אפשר לפנות אליך אם נצטרך?", name: "phone", type: "text", placeholder: "מספר טלפון שיש לך עליו וואטסאפ 📱" },
  { label: "ולמקרה שנצטרך – איפה אתה גר ביומיום?", name: "homeAddress", type: "text", placeholder: "רק לצורך ניסוח החוזה. לא נשתמש בזה מעבר" },
  { label: "איפה נמצא הנכס שאתה משכיר?", name: "propertyAddress", type: "text", placeholder: "עיר, רחוב, מספר, דירה – כמה שיותר מדויק 🏠" },
  { label: "יש חניה ששייכת לדירה?", name: "parking", type: "select", options: ["כן", "לא"], placeholder: "אם כן – נכניס אותה לחוזה" },
  { label: "יש גם מחסן שמגיע עם הדירה?", name: "storage", type: "select", options: ["כן", "לא"], placeholder: "לא חובה, אבל שווה לציין אם יש" },
  { label: "באיזו קומה הדירה שלך נמצאת?", name: "floor", type: "number", placeholder: "אם זה בניין, באיזו קומה היא? אפשר גם 'קרקע'" },
  { label: "יש מעלית בבניין?", name: "elevator", type: "select", options: ["כן", "לא"], placeholder: "כדי שהשוכרים לא יופתעו..." },
  { label: "השארת בדירה משהו שתרצה לציין? נגיד רהיטים או מכשירים?", name: "leftItems", type: "multiselect", options: ["מזגן", "ספה", "כריים", "תנור", "מקרר", "אחר"], icons: { "מזגן": "FaSnowflake", "ספה": "FaCouch", "כריים": "FaUtensils", "תנור": "FaBurn", "מקרר": "FaRegSnowflake", "אחר": "FaRegPlusSquare" }, placeholder: "למשל: מיטה זוגית, ארון, מקרר..." },
  { label: "מי השוכר שאתה סוגר איתו את החוזה?", name: "tenantName", type: "text", placeholder: "שם מלא של כל שוכר" },
  { label: "מה מספר תעודת הזהות של השוכר?", name: "tenantIdNumber", type: "text", placeholder: "מספר ת.ז. של השוכר" },
  { label: "כמה דיירים אתה הולך להכניס לחוזה?", name: "tenantCount", type: "number", placeholder: "אפשר שוכר אחד או כמה – תלוי במצב" },
  { label: "מה הכתובת הנוכחית של הדייר שלך?", name: "tenantAddress", type: "text", placeholder: "כתובת נוכחית של השוכר, לצרכי החוזה בלבד" },
  { label: "יש מישהו אחר שמשלם בשבילו?", name: "otherPayer", type: "select", options: ["כן", "לא"], placeholder: "למשל הורה או גוף תומך" },
  { label: "מתי השוכר שלך נכנס לגור בדירה?", name: "moveInDate", type: "date", placeholder: "תאריך התחלה של השכירות" },
  { label: "לכמה זמן אתם סוגרים את החוזה?", name: "contractDuration", type: "number", placeholder: "רוב החוזים הם לשנה – אבל זה לגמרי תלוי בך" },
  { label: "כמה שכר דירה אתה גובה כל חודש?", name: "monthlyRent", type: "text", placeholder: "כמה ייכנס לך לחשבון כל חודש 💸" },
  { label: "באיזה תאריך בכל חודש תרצה לקבל את התשלום?", name: "rentDueDay", type: "text", placeholder: "למשל: בכל 1 לחודש" },
  { label: "מה הדרך הכי נוחה לך לקבל את התשלום?", name: "preferredPaymentMethod", type: "select", options: ["העברה בנקאית", "שיקים", "אחר"], placeholder: "מה שהכי נוח לך" },
  { label: "איך השוכר יעביר את התשלום?", name: "paymentDetails", type: "text", placeholder: "למשל: צ׳קים, העברה בנקאית, פיקדון" },
  { label: "מתי אתה מצפה לקבל את התשלום הראשון?", name: "firstPaymentDate", type: "date", placeholder: "מתי יועבר התשלום הראשון בפועל" },
  { label: "רוצה להשאיר אופציה להארכת חוזה?", name: "extensionOption", type: "select", options: ["כן", "לא"], placeholder: "כדי לאפשר לשוכר להמשיך בלי חוזה חדש" },
  { label: "יש תוספות לשכר הדירה בהארכה?", name: "extensionRentAddition", type: "text", placeholder: "אם יש אופציה – תוכל לציין סכום חדש" },
  { label: "מה משאיר אותך רגוע?", name: "guarantees", type: "multiselect", options: ["צ׳ק ביטחון", "שטר חוב", "ערבות בנקאית", "ערב"], placeholder: "בחר את הבטחונות שתרצה לקבל" },
  { label: "רשום כמה כל בטחון שווה – לדוגמה: 10,000 ש״ח לצ׳ק ביטחון", name: "guaranteeAmounts", type: "text", placeholder: "לדוגמה: 10,000 ש״ח לצ׳ק ביטחון" },
  { label: "יש לך דרישה לערב בחוזה?", name: "requireGuarantor", type: "select", options: ["כן", "לא"], placeholder: "אם כן – נבקש את פרטיו" },
  { label: "אם יש ערב – איזה סוג אתה מעדיף?", name: "guarantorType", type: "select", options: ["ערבות רגילה", "ערבות אוואל"], placeholder: "למשל: ערבות אוואל, ערבות רגילה" },
  { label: "תן לנו את הפרטים של הערב – שם, טלפון, תעודת זהות וכתובת", name: "guarantorDetails", type: "text", placeholder: "שם, טלפון, כתובת, תעודת זהות" },
  { label: "אם השוכר מתעכב בפינוי – כמה זה עולה?", name: "lateEvictionPenalty", type: "text", placeholder: "פיצוי יומי – לפי שיקולך" },
  { label: "מאפשר להכניס בעלי חיים לדירה?", name: "allowPets", type: "select", options: ["כן", "לא"], placeholder: "שיהיה ברור לכולם מראש 🐶" },
  { label: "צפוי שיפוץ או תמ״א בזמן השכירות?", name: "expectedRenovation", type: "select", options: ["כן", "לא"], placeholder: "כדי למנוע הפתעות – עדיף להכניס לחוזה" },
  { label: "יש משהו מיוחד שתרצה שנכניס לחוזה?", name: "specialClause", type: "text", placeholder: "כל דבר שתרצה להבהיר מראש – זו ההזדמנות" },
  { label: "רוצה שנכניס סעיף על ביטוח למקרה של נזק בדירה?", name: "insuranceClause", type: "select", options: ["כן", "לא"], placeholder: "במקרים של נזק לדירה או לתכולה" },
  { label: "יש כללים שאתה רוצה להבהיר מראש?", name: "houseRules", type: "text", placeholder: "למשל: לא לעשן, לא לארח, לא להכניס בעלי חיים" },
  { label: "איך תרצה לקבל את החוזה לחתימה?", name: "contractDelivery", type: "multiselect", options: ["שלח לי PDF", "חתימה דיגיטלית", "שליחה לשוכר"], placeholder: "PDF למייל? חתימה דיגיטלית? שליחה לשוכר?" },
  { label: "איך לשלוח לך את החוזה כשהוא מוכן?", name: "contractSendMethod", type: "select", options: ["מייל", "וואטסאפ", "שניהם"], placeholder: "מייל, וואטסאפ, או שניהם" },
  { label: "יש משהו נוסף שחשוב לך להוסיף לפני שנסיים?", name: "finalNotes", type: "text", placeholder: "כל דבר נוסף שאתה רוצה שייכנס למסמך" },
  // ... (continue for all questions in the CSV, matching order and type)
]; 